Fix issue in install script where only the last dotfile was installed
Supports #37.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -121,11 +121,11 @@ function install_dotfiles()
                 abort "'$selected_dotfile' archival failure"
             fi
         fi
-    done
 
-    if ! ln -s "$repository/$selected_dotfile" "$dotfile" > "/dev/null"; then
-        abort "'$selected_dotfile' installation failure"
-    fi
+        if ! ln -s "$repository/$selected_dotfile" "$dotfile" > "/dev/null"; then
+            abort "'$selected_dotfile' installation failure"
+        fi
+    done
 }
 
 function main()
