Cleanup scripts
Supports #37.

diff --git a/git/hooks/install b/git/hooks/install
--- a/git/hooks/install
+++ b/git/hooks/install
@@ -19,17 +19,17 @@
 
 function error()
 {
-    local -r param_message="$1"
+    local -r message="$1"
 
-    ( >&2 echo "$MNEMONIC: $param_message" )
+    ( >&2 echo "$mnemonic: $message" )
 }
 
 function abort()
 {
     if [[ "$#" -gt 0 ]]; then
-        local -r param_message="$1"
+        local -r message="$1"
 
-        error "$param_message, aborting"
+        error "$message, aborting"
     fi
 
     exit 1
@@ -38,36 +38,45 @@ function abort()
 function display_help_text()
 {
     echo "NAME"
-    echo "    $MNEMONIC - Install the dotfiles repository's Git hooks."
+    echo "    $mnemonic - Install the dotfiles repository's Git hooks."
     echo "SYNOPSIS"
-    echo "    $MNEMONIC --help"
-    echo "    $MNEMONIC --all"
-    echo "    $MNEMONIC [<hooks>]"
+    echo "    $mnemonic --help"
+    echo "    $mnemonic --version"
+    echo "    $mnemonic --all"
+    echo "    $mnemonic [<hooks>]"
     echo "OPTIONS"
     echo "    --all"
     echo "        Install all supported hooks."
     echo "    --help"
     echo "        Display this help text."
+    echo "    --version"
+    echo "        Display the version of this script."
     echo "    <hooks>"
     echo "        The whitespace separated list of hooks to install. The following hooks"
     echo "        are supported:"
 
-    for hook in "${SUPPORTED_HOOKS[@]}"; do
+    for hook in "${supported_hooks[@]}"; do
         echo "            $hook"
     done
 
     echo "EXAMPLES"
-    echo "    $MNEMONIC --help"
-    echo "    $MNEMONIC --all"
-    echo "    $MNEMONIC ${SUPPORTED_HOOKS[*]}"
+    echo "    $mnemonic --help"
+    echo "    $mnemonic --version"
+    echo "    $mnemonic --all"
+    echo "    $mnemonic ${supported_hooks[*]}"
+}
+
+function display_version()
+{
+    echo "$mnemonic, version $version"
 }
 
 function valid_hook()
 {
-    local -r param_hook="$1"
+    local -r hook="$1"
 
-    for hook in "${SUPPORTED_HOOKS[@]}"; do
-        if [[ "$param_hook" == "$hook" ]]; then
+    for supported_hook in "${supported_hooks[@]}"; do
+        if [[ "$hook" == "$supported_hook" ]]; then
             return 0
         fi
     done
@@ -77,52 +86,50 @@ function valid_hook()
 
 function validate_hooks()
 {
-    while [[ "$#" -gt 0 ]]; do
-        local param_hook="$1"
-        shift
-
-        if ! valid_hook "$param_hook"; then
-            abort "'$param_hook' is not a supported hook"
+    for hook in "${selected_hooks[@]}"; do
+        if ! valid_hook "$hook"; then
+            abort "'$hook' is not a supported hook"
         fi
     done
 }
 
 function install_hooks()
 {
-    while [[ "$#" -gt 0 ]]; do
-        local param_hook="$1"
-        shift
+    for hook in "${selected_hooks[@]}"; do
+        rm -f "$repository/.git/hooks/$hook"
 
-        rm -f "$REPOSITORY/.git/hooks/$param_hook"
-
-        if ! ln -s "$HOOKS/$param_hook" "$REPOSITORY/.git/hooks/$param_hook" >/dev/null 2>&1; then
-            abort "'$param_hook' installation failed"
+        if ! ln -s "$hooks/$hook" "$repository/.git/hooks/$hook" > "/dev/null"; then
+            abort "'$hook' installation failure"
         fi
     done
 }
 
 function main()
 {
-    SCRIPT=$( readlink -f "$0" ); readonly SCRIPT
-    MNEMONIC=$( basename "$SCRIPT" ); readonly MNEMONIC
-    HOOKS=$( dirname "$SCRIPT" ); readonly HOOKS
-    REPOSITORY=$( readlink -f "$HOOKS/../.." ); readonly REPOSITORY
+    local -r script=$( readlink -f "$0" )
+    local -r mnemonic=$( basename "$script" )
+    local -r hooks=$( dirname "$script" )
+    local -r repository=$( readlink -f "$hooks/../.." )
+    local -r version=$( git -C "$repository" describe --always --dirty --broken )
 
-    mapfile -t SUPPORTED_HOOKS < <( git -C "$REPOSITORY" ls-files -- 'git/hooks/' | xargs -r -d '\n' -I '{}' find "$REPOSITORY/"{} -name "$MNEMONIC" -prune -o -executable -printf '%f\n' ); readonly SUPPORTED_HOOKS
+    local supported_hooks; mapfile -t supported_hooks < <( git -C "$repository" ls-files 'git/hooks/' ':!:git/hooks/install' | xargs -r -d '\n' -I '{}' find "$repository/{}" -executable -printf '%f\n' ); readonly supported_hooks
 
-    local hooks=()
+    local selected_hooks=()
 
     while [[ "$#" -gt 0 ]]; do
-        local argument="$1"
-        shift
+        local argument="$1"; shift
 
         case "$argument" in
             --help)
                 display_help_text
                 exit
                 ;;
+            --version)
+                display_version
+                exit
+                ;;
             --all)
-                hooks=( "${SUPPORTED_HOOKS[@]}" )
+                selected_hooks=( "${supported_hooks[@]}" )
                 break
                 ;;
             --*)
@@ -130,19 +137,16 @@ function main()
             -*)
                 abort "'$argument' is not a supported option"
                 ;;
-            "$MNEMONIC")
-                abort "'$MNEMONIC' is not a hook"
-                ;;
             *)
-                hooks+=( "$argument" )
+                selected_hooks+=( "$argument" )
                 ;;
         esac
     done
 
-    readonly hooks
+    readonly selected_hooks
 
-    validate_hooks "${hooks[@]}"
-    install_hooks "${hooks[@]}"
+    validate_hooks
+    install_hooks
 }
 
 main "$@"
